### PR TITLE
Correct greedy yellowing of repeated letters (fixes #1)

### LINKED ISSUE #1: Double letters incorrectly shown yellow
With the answer proxy, the display shows the second o in proof as yellow. In game it shows as a miss.

### PR DESCRIPTION
**Pull request by jakewilliami**
I really appreciate this project, and even more than that, I was admirable to find it was written in Rust (which I too am in the process of learning).  I saw you had a couple of issues (one bug, and one small thing), and thought I would help out, as a token of my gratitude;
  - Correct greedy yellowing of repeated letters in guess (fixes #1)
  - Added a wordlist that more closely resembles the Wordle wordlist (addresses #2; uses the Scrabble dictionary, obtained from [here](sourceforge.net/projects/scrabbledict/))
    - Retain the old wordlist (renamed)
  - More robust loading of wordlist (ensure we filter all words that are not of length five)

NOTE: The fix for #1 seems to work, but you may have more robust tests than I do, so do test this as well.  Also, while thinking of a solution for #1, I changed around line 85, but that didn't seem to fix it, so then I changed around line 141, and that seemed to work.

All the best!

### CODE REVIEW

**Comment by jsha** [comment]
Ooh, thanks for fixing those! Your fix for #1 looks good. As for #2: I just recently made a change to use the list of possible answers from the Wordle source code (500f54be05b746948d6635c6f832f27c0acc17d4). I think that's a better solution than the Scrabble dictionary.

I'll test out your change locally and cherry-pick 61c3dab assuming it looks good.

**Comment by jsha** [comment]
There seems to be a bug in your added logic. For instance, try http://localhost:8080/analyze/soppy,pleat. I get:

image

One of those P's should be yellow.

**Comment by jsha** [comment]
Also PS! Thanks for the kind words about the site; they mean a lot. And welcome to Rust, I hope you find the language enjoyable.

**Comment by jakewilliami** [comment]
> There seems to be a bug in your added logic. For instance, try http://localhost:8080/analyze/soppy,pleat. I get:
Ohh, good catch!  I'll have a look at the code now.

**Comment by jakewilliami** [comment]
I think I fixed it (see f7efe14).
Screen Shot 2022-02-06 at 3 36 05 PM
Screen Shot 2022-02-06 at 3 36 30 PM
<details> 
  <summary>This seems to be consistent with Wordle's policy on double letters (see below—note: spoiler for today's Wordle!)</summary>
IMG_5788
</details>

**Comment by jsha** [comment]
The updated version looks correct, thanks! I've cherry-picked the "yellow letters" commits manually. I'm omitting the change to switch to the Scrabble dictionary for now. I think I'd like to make a change to the dictionary but I'm not sure in which direction yet.

**Pull request closed without merging**
